- id: "Hass Startup Notification"
  alias: 'Hass Startup Notification'
  trigger:
    - platform: homeassistant
      event: start
  action:
    service: notify.ha_message_group
    data:
      title: "*Info / Warning*"
      message: "Home Assistant ist gestartet"

- id: "Hass Shutdown Notification"
  alias: 'Hass Shutdown Notification'
  trigger:
    - platform: homeassistant
      event: shutdown
  action:
    service: notify.ha_message_group
    data:
      title: "*Info / Warning*"
      message: "Home Assistant ist herunter gefahren"

- alias: 'Send notification when sun rises'
  trigger:
    platform: sun
    event: sunrise
    offset: '+00:00:00'
  action:
    service: notify.ha_message_group
    data:
      title: '*Home Assistant Info*'
      message: 'Die Sonne ist aufgegangen.'

- alias: 'Send notification when sun sets'
  trigger:
    platform: sun
    event: sunset
    offset: '+00:00:00'
  action:
    service: notify.ha_message_group
    data:
      title: '*Home Assistant Info*'
      message: 'Die Sonne ist untergegangen.'

- alias: 'Telegram bot that reply pong to ping'
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/ping'
  action:
    - service: notify.ha_message_group
      data:
        title: '*Home Assistant Test*'
        message: 'pong'

- alias: "EAW Abholtermine - Abfall"
  trigger:
    - platform: time
      at: "17:00:00"
  condition:
    condition: template
    value_template: >
      {% set eaw = [states.sensor.ics_1, states.sensor.ics_2, states.sensor.ics_3, states.sensor.ics_4] %}
      {{ eaw | selectattr('attributes.remaining','<', 3) | list | length >= 1 }}
  action:
    - service: notify.ha_message_group
      data_template:
        title: '*EAW Abholtermine*'
        message: >
          {% set eaw = [states.sensor.ics_1, states.sensor.ics_2, states.sensor.ics_3, states.sensor.ics_4] %}
          {% set items = eaw | selectattr('attributes.remaining','<', 3) | map(attribute='attributes.friendly_name') | list | join(', ') %}
          Abfall rausstellen {{ items }}