button_card_templates: !include_dir_merge_named ui_lovelace_minimalist/includes/
title: ""
views: !include_dir_list ui_lovelace_minimalist/dashboard/


#### OLD ####

##views:
##  - !include lovelace_minimalist/dashboard/view_home.yaml
##  - !include lovelace_minimalist/dashboard/view_rooms.yaml
##  - !include lovelace_minimalist/dashboard/view_system.yaml
##
##  # Chips
##  - !include lovelace_minimalist/dashboard/view_climate.yaml
##  - !include lovelace_minimalist/dashboard/view_presense.yaml
##  - !include lovelace_minimalist/dashboard/view_lights.yaml
##  - !include lovelace_minimalist/dashboard/view_motion.yaml
##
##  # Rooms
##  - !include lovelace_minimalist/dashboard/view_living_room.yaml
##  - !include lovelace_minimalist/dashboard/view_kitchen.yaml
##  - !include lovelace_minimalist/dashboard/view_hallway.yaml
##  - !include lovelace_minimalist/dashboard/view_bedroom.yaml
##  - !include lovelace_minimalist/dashboard/view_kids_room.yaml
##  - !include lovelace_minimalist/dashboard/view_work_room.yaml
##
##  # System
##  - !include lovelace_minimalist/dashboard/view_scheduler.yaml
##  - !include lovelace_minimalist/dashboard/view_homeassistant.yaml
##  - !include lovelace_minimalist/dashboard/view_wallpanel.yaml
##  - !include lovelace_minimalist/dashboard/view_nas.yaml
##  - !include lovelace_minimalist/dashboard/view_batteries.yaml
##  - !include lovelace_minimalist/dashboard/view_tasmota.yaml
##  - !include lovelace_minimalist/dashboard/view_zigbee2mqtt.yaml
##  - !include lovelace_minimalist/dashboard/view_energy.yaml
##
##  # Kiosk
##  - !include lovelace_minimalist/dashboard/view_kiosk.yaml

##button_card_templates:
##  header:
##    styles:
##      card:
##        - height: 30px
##        - font-size: 14px
##    color_type: label-card
##    color: "var(--secondary-background-color)"
##  header_clickable:
##    color_type: card
##    color: "var(--secondary-background-color)"
##    show_icon: false
##    styles:
##      card:
##        - height: 30px
##        - font-size: 14px
##        - background-color: "var(--ha-card-background)"
##  esp:
##    styles:
##      card:
##        - height: 35px
##        - font-size: 14px
##    color_type: icon
##    show_name: false
##    show_icon: false
##    show_state: true
##  people_state:
##    show_state: true
##    show_icon: true
##    show_name: false
##    show_entity_picture: true
##    tap_action:
##      action: more-info
##    styles:
##      card:
##        - font-size: 14px
##    style: |
##      img {
##        width: 100% !important;
##      }
##      #img-cell {
##        border-radius: 50px;
##        height: 50px !important;
##        width: 50px !important;
##      }
##      #state {
##        padding-top: 5px;
##      }
##  people_button:
##    show_state: false
##    show_icon: false
##    show_name: false
##    size: 16px
##    tap_action:
##      action: more-info
##    styles:
##      card:
##        - height: 30x
##        - font-size: 12px
##        - box-shadow: unset
##  dash_button:
##    size: 25px
##    color_type: card
##    tap_action:
##      action: more-info
##    hold_action:
##      action: toggle
##    styles:
##      card:
##        - height: 70px
##        - font-size: 11px
##        - margin: 0px
##        - background: >
##            [[[
##            if (entity.state == "on") return "var(--accent-color)";
##            else return "var(--ha-card-background)";
##            ]]]
##    style: !include lovelace/includes/style.yaml
##  popup_button:
##    size: 25px
##    color_type: card
##    tap_action:
##      action: more-info
##    styles:
##      card:
##        - height: 70px
##        - font-size: 11px
##        - background: >
##            [[[
##            if (entity.state == "on") return "var(--accent-color)";
##            else return "var(--ha-card-background)";
##            ]]]
##    style: !include lovelace/includes/style.yaml
##  timer:
##    color_type: card
##    color: "var(--color-red-bright-1)"
##    size: 25px
##    show_icon: false
##    show_name: false
##    show_state: true
##    styles:
##      card:
##        - height: 20px
##        - font-size: 11px
##        - font-weight: bold
##  pi-hole:
##    size: 30px
##    styles:
##      card:
##        - font-size: 12px
##  power:
##    styles:
##      card:
##        - height: 40px
##        - font-size: 13.5px
##      name:
##        - color: var(--secondary-text-color)
##        - font-size: 10px
##    show_name: true
##    show_icon: false
##    show_state: true
##
##title: ""
##views: !include_dir_list lovelace/views/
##