sensor:

  - platform: template
    sensors:

      # Number of Media-Player On
      number_of_media_player_on:
        friendly_name: "Number of Media Devices On"
        icon_template: mdi:cast-audio
        value_template: >-
          {% set count = namespace(value=0) %}
          {% for entity_id in state_attr('group.all_media_player_entities','entity_id') %}
            {% if (states(entity_id) == 'on') %}
              {% set count.value = count.value + 1 %}
            {% endif %}
          {% endfor %}
          {{ count.value }}
