# Computer Basti NUC @TODO Icon ändern und PC herunterfahren Funktion
- platform: wake_on_lan
  name: "Basti NUC"
  mac: "94:C6:91:10:5C:45"
  host: 192.168.178.93
  turn_off:
    service: script.pc_off

#- platform: template
#  switches:
#    basti_nuc:
#      friendly_name: Basti NUC
#      value_template: "{{ is_state('device_tracker.basti_nuc', 'home') }}"
#      #icon_template: mdi:arm-flex
#      turn_on:
#        service: switch.turn_on
#        data:
#          entity_id: switch.turn_on
#      turn_off:
#        service: switch.turn_off
#        data:
#          entity_id: switch.turn_off
#          data:
#            mac: '94:C6:91:10:5C:45'
#            host: 192.168.178.93
#            broadcast_address: 255.255.255.255
#      icon_template: >-
#        {% if is_state('device_tracker.basti_nuc', 'home') %}
#          mdi:arm-flex
#        {% else %}
#          mdi:apple
#        {% endif %}