# Computer Basti NUC @TODO Icon ändern und PC herunterfahren Funktion
- platform: wake_on_lan
  name: "Computer-NUC"
  mac: !secret computer_computer_nuc_mac
  host: !secret computer_computer_nuc_ip
  turn_off:
    service: script.pc_off

- platform: wake_on_lan
  name: "Basti-PC"
  mac: !secret computer_basti_pc_mac
  host: !secret computer_basti_pc_ip
  turn_off:
    service: hassio.addon_stdin
    data:
      addon: core_rpc_shutdown
      input: basti-pc

#- platform: template
#  switches:
#    basti_nuc:
#      friendly_name: Basti NUC
#      value_template: "{{ is_state('device_tracker.basti_nuc', 'home') }}"
#      #icon_template: mdi:arm-flex
#      turn_on:
#        service: switch.turn_on
#        data:
#          entity_id: switch.turn_on
#      turn_off:
#        service: switch.turn_off
#        data:
#          entity_id: switch.turn_off
#          data:
#            mac:
#            host:
#            broadcast_address: 255.255.255.255
#      icon_template: >-
#        {% if is_state('device_tracker.basti_nuc', 'home') %}
#          mdi:arm-flex
#        {% else %}
#          mdi:apple
#        {% endif %}