# Computer Sebastian NUC @TODO Icon ändern und PC herunterfahren Funktion
- platform: wake_on_lan
  name: Computer - NUC
  mac: !secret computer_computer_nuc_mac
  host: !secret computer_computer_nuc_ip
  turn_off:
    service: script.pc_off

# Main Computer Sebastian
- platform: wake_on_lan
  name: Computer - Sebastian PC
  mac: !secret computer_sebastian_pc_mac
  host: !secret computer_sebastian_pc_ip
  turn_off:
    service: hassio.addon_stdin
    data:
      addon: core_rpc_shutdown
      # @Todo für was steht das input?
      input: computer_sebastian_pc

#- platform: template
#  switches:
#    basti_nuc:
#      friendly_name: Basti NUC
#      value_template: "{{ is_state('device_tracker.basti_nuc', 'home') }}"
#      #icon_template: mdi:arm-flex
#      turn_on:
#        service: switch.turn_on
#        data:
#          entity_id: switch.turn_on
#      turn_off:
#        service: switch.turn_off
#        data:
#          entity_id: switch.turn_off
#          data:
#            mac:
#            host:
#            broadcast_address: 255.255.255.255
#      icon_template: >-
#        {% if is_state('device_tracker.basti_nuc', 'home') %}
#          mdi:arm-flex
#        {% else %}
#          mdi:apple
#        {% endif %}

# DKD Laptop Sebastian
- platform: wake_on_lan
  name: Computer - dkd Laptop
  mac: !secret computer_dkd_laptop_mac
  host: !secret computer_dkd_laptop_ip

