sensor:

  - platform: template
    sensors:

      # Number of Lights On
      number_of_lights_on:
        friendly_name: "Number of lights on"
        icon_template: mdi:lightbulb
        value_template: >-
          {% set count = namespace(value=0) %}
          {% for entity_id in state_attr('group.all_light_entities','entity_id') %}
            {% if (states(entity_id) == 'on') %}
              {% set count.value = count.value + 1 %}
            {% endif %}
          {% endfor %}
          {{ count.value }}

      # Only Light On
      only_light_on:
        friendly_name: "Only Light On"
        icon_template: mdi:lightbulb
        value_template: >-
          {% for entity_id in state_attr('group.all_light_entities','entity_id') %}
            {% if (states(entity_id) == 'on') %}
              {{ states[entity_id].attributes.friendly_name }}
            {% endif %}
          {% endfor %}

      ## Number of Lights On - Office Room
      #number_of_lights_on_work_room:
      #  friendly_name: "Number of lights on Office Room"
      #  icon_template: mdi:lightbulb
      #  value_template: >-
      #    {% set count = namespace(value=0) %}
      #    {% for entity_id in state_attr('group.work_room_lights','entity_id') %}
      #      {% if (states(entity_id) == 'on') %}
      #        {% set count.value = count.value + 1 %}
      #      {% endif %}
      #    {% endfor %}
      #    {{ count.value }}
      #
      ## Number of Lights On - Hallway
      #number_of_lights_on_hallway:
      #  friendly_name: "Number of lights on Hallway"
      #  icon_template: mdi:lightbulb
      #  value_template: >-
      #    {% set count = namespace(value=0) %}
      #    {% for entity_id in state_attr('group.hallway_lights','entity_id') %}
      #      {% if (states(entity_id) == 'on') %}
      #        {% set count.value = count.value + 1 %}
      #      {% endif %}
      #    {% endfor %}
      #    {{ count.value }}
