sensor:

  - platform: template
    sensors:

      # Number of Motion On
      number_of_motion_on:
        friendly_name: "Number of Motion Sensors On"
        icon_template: mdi:motion-sensor
        value_template: >-
          {% set count = namespace(value=0) %}
          {% for entity_id in state_attr('group.all_motion_entities','entity_id') %}
            {% if (states(entity_id) == 'on') %}
              {% set count.value = count.value + 1 %}
            {% endif %}
          {% endfor %}
          {{ count.value }}

      # Only Motion On
      only_motion_on:
        friendly_name: "Only Motion Sensor On"
        icon_template: mdi:motion-sensor
        value_template: >-
          {% for entity_id in state_attr('group.all_motion_entities','entity_id') %}
            {% if (states(entity_id) == 'on') %}
              {{ states[entity_id].attributes.friendly_name }}
            {% endif %}
          {% endfor %}

      # Number of Motion
      number_of_motion:
        friendly_name: "Number of Motion Sensors"
        icon_template: mdi:motion-sensor
        value_template: >-
          {% set count = namespace(value=0) %}
          {% for entity_id in state_attr('group.all_motion_entities','entity_id') %}
            {% set count.value = count.value + 1 %}
          {% endfor %}
          {{ count.value }}
