- platform: template
  sensors:
    buro_dect301_1_temperature:
      value_template: "{{state_attr('climate.buro_dect301_1', 'temperature') }}"
      friendly_name: "Temperatur"
      unit_of_measurement: '째C'
    buro_dect301_1_current_temperature:
      value_template: "{{state_attr('climate.buro_dect301_1', 'current_temperature') }}"
      friendly_name: "Temperatur"
      unit_of_measurement: '째C'
    buro_dect301_1_battery_level:
      value_template: "{{state_attr('climate.buro_dect301_1', 'battery_level') }}"
      friendly_name: "Batterie"
      unit_of_measurement: '%'
    schlafzimmer_dect301_1_temperature:
      value_template: "{{state_attr('climate.schlafzimmer_dect301_1', 'temperature') }}"
      friendly_name: "Temperatur"
      unit_of_measurement: '째C'
<<<<<<< HEAD
    schlafzimmer_dect301_1_current_temperature:
      value_template: "{{state_attr('climate.schlafzimmer_dect301_1', 'current_temperature') }}"
      friendly_name: "Temperatur"
      unit_of_measurement: '째C'
=======
>>>>>>> 579106b177a350199a98d2a7dfd757c615d2e586
    schlafzimmer_dect301_1_battery_level:
      value_template: "{{state_attr('climate.schlafzimmer_dect301_1', 'battery_level') }}"
      friendly_name: "Batterie"
      unit_of_measurement: '%'