- platform: template
  sensors:
    net_download_max:
      value_template: "{{ states('sensor.ingeniumdesign_max_kbit_s_received') | float / 1000 | round(1) }}"
      unit_of_measurement: "Mbit/s"
      friendly_name: "Down"
      icon_template: mdi:download
  
    net_upload_max:
      value_template: "{{ states('sensor.ingeniumdesign_max_kbit_s_sent') | float / 1000 | round(1) }}"
      unit_of_measurement: "Mbit/s"
      friendly_name: "Up"
      icon_template: mdi:upload

    net_download_cur:
      value_template: "{{ states('sensor.ingeniumdesign_kb_s_received') | float / 1000 | round(1) }}"
      unit_of_measurement: "Mbit/s"
      friendly_name: "Download"
      icon_template: mdi:download
    
    net_upload_cur:
      value_template: "{{ states('sensor.ingeniumdesign_kb_s_sent') | float / 1000 | round(1) }}"
      unit_of_measurement: "Mbit/s"
      friendly_name: "Upload"
      icon_template: mdi:upload
    
    net_received:
      value_template: "{{ states('sensor.ingeniumdesign_gb_received') | float | round(0) }}"
      unit_of_measurement: "GB"
      friendly_name: "Empfangen"
      icon_template: mdi:file
    
    net_sent:
      value_template: "{{ states('sensor.ingeniumdesign_gb_sent') | float | round(0) }}"
      unit_of_measurement: "GB"
      friendly_name: "Gesendet"
      icon_template: mdi:file

    net_uptime:
      value_template: "{{states('sensor.ingeniumdesign_connection_uptime').split('T')[1].split('+')[0]}}"
      #value_template: "{{ as_timestamp(strptime( states('sensor.ingeniumdesign_connection_uptime'), '%Y-%m-%d %H:%M:%S')) | timestamp_custom('%Y-%m-%d %H:%M:%S') }}"
      unit_of_measurement: "Tage"
      friendly_name: "Verbunden"
      icon_template: mdi:calendar

- platform: filter
  name: "net_download_cur_filtered"
  entity_id: sensor.net_download_cur
  filters:
    - filter: range
      lower_bound: 0
      upper_bound: 100