- platform: template
  sensors:
    net_download_max:
<<<<<<< HEAD
      value_template: "{{ states('sensor.ingeniumdesign_max_kbit_s_received') | float / 1000 | round(1) }}"
=======
      value_template: "{{ (state_attr('sensor.ingeniumdesign_max_kbit_s_received', 'max_byte_rate_down')|float / 125000)|round(1) }}"
>>>>>>> 579106b177a350199a98d2a7dfd757c615d2e586
      unit_of_measurement: "Mbit/s"
      friendly_name: "Down"
      icon_template: mdi:download
  
    net_upload_max:
<<<<<<< HEAD
      value_template: "{{ states('sensor.ingeniumdesign_max_kbit_s_sent') | float / 1000 | round(1) }}"
      unit_of_measurement: "Mbit/s"
      friendly_name: "Up"
      icon_template: mdi:upload
=======
        value_template: "{{ (state_attr('sensor.ingeniumdesign_max_kbit_s_sent', 'max_byte_rate_up')|float / 125000)|round(1) }}"
        unit_of_measurement: "Mbit/s"
        friendly_name: "Up"
        icon_template: mdi:upload
>>>>>>> 579106b177a350199a98d2a7dfd757c615d2e586

    net_download_cur:
      value_template: "{{ states('sensor.ingeniumdesign_kb_s_received') | float / 1000 | round(1) }}"
      unit_of_measurement: "Mbit/s"
      friendly_name: "Download"
      icon_template: mdi:download
    
    net_upload_cur:
      value_template: "{{ states('sensor.ingeniumdesign_kb_s_sent') | float / 1000 | round(1) }}"
      unit_of_measurement: "Mbit/s"
      friendly_name: "Upload"
      icon_template: mdi:upload
    
    net_received:
<<<<<<< HEAD
      value_template: "{{ states('sensor.ingeniumdesign_gb_received') | float | round(0) }}"
      unit_of_measurement: "GB"
      friendly_name: "Empfangen"
      icon_template: mdi:file
    
    net_sent:
      value_template: "{{ states('sensor.ingeniumdesign_gb_sent') | float | round(0) }}"
      unit_of_measurement: "GB"
      friendly_name: "Gesendet"
      icon_template: mdi:file

    net_uptime:
      value_template: "{{states('sensor.ingeniumdesign_connection_uptime').split('T')[1].split('+')[0]}}"
      #value_template: "{{ as_timestamp(strptime( states('sensor.ingeniumdesign_connection_uptime'), '%Y-%m-%d %H:%M:%S')) | timestamp_custom('%Y-%m-%d %H:%M:%S') }}"
      unit_of_measurement: "Tage"
      friendly_name: "Verbunden"
      icon_template: mdi:calendar
=======
        value_template: "{{ (state_attr('sensor.ingeniumdesign_max_kbit_s_received', 'bytes_received')|float / 1000000)|round(0) }}"
        unit_of_measurement: "MB"
        friendly_name: "Empfangen"
        icon_template: mdi:file
    
    net_sent:
        value_template: "{{ (state_attr('sensor.ingeniumdesign_max_kbit_s_sent', 'bytes_sent')|float / 1000000)|round(0) }}"
        unit_of_measurement: "MB"
        friendly_name: "Gesendet"
        icon_template: mdi:file

    net_uptime:
        value_template: "{{ (state_attr('sensor.ingeniumdesign_connection_uptime', 'uptime')|float / 86400)|round(1) }}"
        unit_of_measurement: "Tage"
        friendly_name: "Verbunden"
        icon_template: mdi:calendar
>>>>>>> 579106b177a350199a98d2a7dfd757c615d2e586

- platform: filter
  name: "net_download_cur_filtered"
  entity_id: sensor.net_download_cur
  filters:
    - filter: range
      lower_bound: 0
      upper_bound: 100