- platform: template
  sensors:
    dwd_weather_temperature:
      value_template: "{{state_attr('weather.dwd_weather_idstein', 'temperature')}}"
      friendly_name: "Temperatur"
      icon_template: mdi:thermometer
      unit_of_measurement: '°C'
    dwd_weather_humidity:
      value_template: "{{state_attr('weather.dwd_weather_idstein', 'humidity')}}"
      friendly_name: "Luftfeuchtigkeit"
      icon_template: mdi:water-percent
      unit_of_measurement: '%'