#########
# GROUP #
#########
group:
  all_persons:
    name: Personen
    entities:
      - person.sebastian_schmal
      - person.julia_schmal

################
# INPUT_SELECT #
################
input_select:
  presence_sebastian:
    options:
      - Zu Hause
      - Angekommen
      - Verlassen
      - Abwesend
      - Lange Abwesend
      - Arbeit
      - Golfen
  presence_julia:
    options:
      - Zu Hause
      - Angekommen
      - Verlassen
      - Abwesend
      - Lange Abwesend
      - Arbeit
      - Janine & Erik
      - Marion & Gerd
      - Doris & Ronny

##########
# SENSOR #
##########
sensor:
  - platform: template
    sensors:
      sebastian_status:
        value_template: '{{ states.input_select.presence_sebastian.state }}'
        friendly_name: 'Sebastian'
      julia_status:
        value_template: '{{ states.input_select.presence_julia.state }}'
        friendly_name: 'Julia'